{% set name = "xcube-multistore" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-multistore/archive/v{{ version }}.tar.gz
  sha256: 9074ec42f9a9929dca16ebc271a6d810ecc125d30d218f1027aa5ace9c28f977

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dask
    - fsspec
    - numpy
    - pyproj
    - tabulate
    - xarray
    - xcube >=1.9.0
    - xcube-cci >=0.11.2
    - xcube-cds >=1.0.0
    - xcube-clms >=0.2.2
    - xcube-stac >=0.2.0
    - xcube-zenodo >=1.0.0
    - yaml

test:
  imports:
    - xcube_multistore
  requires:
    - python {{ python_min }}

about:
  summary: xcube Multi-Source Data Store; Seamlessly Integrating and Harmonizing Data from Multiple Sources
  home: https://github.com/xcube-dev/xcube-multistore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-multistore is a Python package
  dev_url: https://github.com/xcube-dev/xcube-multistore

extra:
  recipe-maintainers:
    - konstntokas
    - forman
    - pont-us
    - thomasstorm
    - TejasMorbagal
