{% set name = "xcube-multistore" %}
{% set version = "0.3.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcube-multistore/archive/v{{ version }}.tar.gz
  sha256: 2ae9ac2e334407556c43fe76637d3b55476a88bfb83568b157a7f52ad9af1e05

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dask
    - fsspec
    - numpy
    - panel
    - pyproj
    - pystac-client
    - tabulate
    - xarray
    - xcube >=1.13.1
    - xcube-resampling >=0.3.2
    - yaml

test:
  imports:
    - xcube_multistore
  requires:
    - python {{ python_min }}

about:
  summary: xcube Multi-Source Data Store; Seamlessly Integrating and Harmonizing Data from Multiple Sources
  home: https://github.com/xcube-dev/xcube-multistore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-multistore is a Python package
  dev_url: https://github.com/xcube-dev/xcube-multistore

extra:
  recipe-maintainers:
    - TonioF
    - clarasb
    - b-yogesh
    - konstntokas
    - forman
    - pont-us
    - thomasstorm
    - TejasMorbagal
